apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- with .Values.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.externalIPs }}
  externalIPs: {{ . | toYaml | nindent 4 }}
  {{- end }}
  ports:
  - name: game-port
    port: {{ .Values.config.gamePort | int }}
    targetPort: game-port
    protocol: UDP
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.config.gamePort | int }}
    {{- end }}
  - name: query-port
    port: {{ .Values.config.queryPort | int }}
    targetPort: query-port
    protocol: UDP
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.config.queryPort| int }}
    {{- end }}
  selector:
    app: "{{ .Chart.Name }}"
