name: Nightly Docker Wine Build

on:
  push:
    branches: [ "main" ]
  # Run at midnight
  schedule:
    - cron: "0 0 * * *"

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      #check out repo
      - name: Checkout code
        uses: actions/checkout@v3

      #Log into Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Add Date Tags
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # Build the Docker image
      - name: Build Docker images with 3 separate tags
        run: |
          docker build --file container/wine/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/enshrouded-server:wine-nightly -t ${{ secrets.DOCKER_USERNAME }}/enshrouded-server:wine-${{ steps.date.outputs.date }} -t ${{ secrets.DOCKER_USERNAME }}/enshrouded-server:wine-latest .

      # Push the Docker image nightly
      - name: Push Docker nightly image 
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/enshrouded-server:wine-nightly

      # Push same image with date tag
      - name: Push Docker image date tag
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/enshrouded-server:wine-${{ steps.date.outputs.date }}

      # Push same image with date tag
      - name: Push Docker image w latest tag
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/enshrouded-server:wine-latest

